plugins { id 'com.android.application' }

android {
    namespace 'com.explapp.bikekidslegacy'
    compileSdk 33

    defaultConfig {
        applicationId 'com.explapp.bikekidslegacy'
        minSdk 19
        targetSdk 28
        versionCode 3
        versionName '3.0.0'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            shrinkResources false
            zipAlignEnabled true
        }
    }

    lintOptions {
        abortOnError true
        checkReleaseBuilds true
        disable 'OldTargetApi'
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
